### ISSUE TITLE
[PE-D][Tester C] Unable to remove all student's tags by typing t/ (or -tag)

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T11-3/tp#203] opened 2023-11-03 19:45 UTC
Not really sure how to use `t/` indicated in UG (unclear) to remove all the student's tags so I tried multiple ways, but still unable to make it work.

![Screenshot 2023-11-03 at 4.41.54 PM.png](https://raw.githubusercontent.com/vivienherq/ped/main/files/05a69e3b-049b-4e9e-8e82-422ff57e68a3.png)

![Screenshot 2023-11-03 at 4.40.30 PM.png](https://raw.githubusercontent.com/vivienherq/ped/main/files/188edcb2-2aef-467d-8a21-53c11a090c3d.png)

![Screenshot 2023-11-03 at 4.40.50 PM.png](https://raw.githubusercontent.com/vivienherq/ped/main/files/01f0aab0-4afa-4d83-b0b5-d5dc0c8c439f.png)

![Screenshot 2023-11-03 at 4.41.02 PM.png](https://raw.githubusercontent.com/vivienherq/ped/main/files/f6f922df-9ab7-4c9a-ba6f-8282a5bd4191.png)

![Screenshot 2023-11-03 at 4.41.40 PM.png](https://raw.githubusercontent.com/vivienherq/ped/main/files/6409555d-b582-421e-9e5b-09a4a56d7bf4.png)

empty -tag doesn't work either (mentioned in a previous bug report)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: vivienherq/ped#7

**Comment by HollaG** [comment] 2023-11-04 15:16
Duplicate of #188

**Closed as completed by HollaG** 2023-11-04 15:16 UTC
